---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 18.13.7
      helm:
        releaseName: loki
        valueFiles:
          - $values/argo/values/logging/loki.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.13.0
      helm:
        releaseName: alloy
        valueFiles:
          - $values/argo/values/logging/alloy.yaml
    - repoURL: git@github.com:GabroveanuRazvan/Homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
