---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 89.2.0
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/argo/values/monitoring/kube-prometheus-stack.yaml
    - repoURL: git@github.com:GabroveanuRazvan/Homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: monitoring-grafana
      namespace: monitoring
      jsonPointers:
        - /data/admin-password
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
