---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rackpeek-pvc
  namespace: rackpeek
  labels:
    app.kubernetes.io/name: rackpeek
    app.kubernetes.io/part-of: rackpeek
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
