---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart TigerVNC
  ansible.builtin.systemd_service:
    name: homelab-vnc.service
    state: restarted
  when: vnc_password_file.stat.exists | default(false)
